### PR TITLE
avoid mapping device while start pause image

### PR DESCRIPTION
**Pull request by Eric-918**
container would start failed ,while mapping device in pause image.

### CODE REVIEW

**Comment by Eric-918** [comment]
I have registered in linuxfoundation, what should i do next ?

**Comment by k82cn** [comment]
@Eric-918 , thanks for your PRs; but I think this PR is for k8s and update godep here :).

**Comment by Eric-918** [comment]
k8s get device info from the config , I don't think this pr suits for k8s . Mapping device by this way is just an expedient for kube-mesos, more work need to do, include on mesos.

**Comment by k82cn** [comment]
old PR, i'd like to close it.

**Pull request closed without merging**
